### ISSUE TITLE
Calls for event info return event id multiple times

### ISSUE THREAD

**Issue by i3iorn** [aiqueneldar/participantcaller#15]
The following columns are returned for all event locations:
eventID: 1
​​​​locationDescription: "nunc ac mattis ornare, lectus ante dictum mi,"
​​​​locationID: 1
​​​​locationName: "ultrices. Vivamus"
​​​​reusable: 0

It should be:
​​​​locationDescription: "nunc ac mattis ornare, lectus ante dictum mi,"
​​​​locationID: 1
​​​​locationName: "ultrices. Vivamus"
​​​​reusable: 0

No reason to return event id for all locations.

_Originally posted by @i3iorn in https://github.com/aiqueneldar/participantcaller/issues/5#issuecomment-539962765_

**Comment by i3iorn** [comment]
Its the same for event_attributes

**Comment by aiqueneldar** [comment]
The reason is that the code fetching the event fetches everything. Which (in my opinion) makes for cleaner code.

As a separate reason, if you get the ID back for every location, you can do some nifty loops since the event ID is part of the data you get back. I'm not saying were ever gonna need to do that. But some options open up if we get the ID back as part of the payload.

**Comment by i3iorn** [comment]
I agree that it is more compact, obviously, but it's less semantic, can lead to unexpected behaviour if the database table is  ever changed.

Best practice from a dba point of  view is to always name the columns you select. This also helps if you don't have the schema committed to memory.

I don't see the benefit of returning the keys more then once but since it neither impacts performance in a meaningful way or ease of use Ill be okay with leaving it as is.

**Comment by aiqueneldar** [comment]
Fixed in commit 3e0fc04
